name: project_3d
description: Flutter 3D beautiful ui using O3D dependency.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  o3d: ^3.1.3
  percent_indicator: ^4.2.5
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi_web: ^0.4.3+1
  sqflite_common_ffi: ^2.3.6
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  http: ^1.2.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/male_basic_walk_30_frames_loop.glb
    - assets/disney_style_character.glb
